# Preprod environment values

replicaCount: 1

image:
  repository: ghcr.io/your-org/sie-operator
  tag: "0.1.0"
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 8081

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: cp.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

env:
  DEFINITION_MANAGER_URL: http://sie-definition-manager:8080
  OIDC_ISSUER_URI: https://login.microsoftonline.com/<preprod-tenant-id>/v2.0
  OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector.monitoring.svc.cluster.local:4317

resources:
  requests:
    cpu: "250m"
    memory: "512Mi"
  limits:
    cpu: "1000m"
    memory: "1Gi"

nodeSelector: {}
tolerations: []
affinity: {}
